In [1]:
import os
import subprocess
import pandas as pd

In [ ]:
###Load file of fasta file description R1 and R2###

df_file = pd.read_csv('file_description.csv', sep=',')
df_file.head()

   Sample_name                     R1_file                     R2_file
0    PPI_T0_R1    fastq/PPI_T0_R1_R1.fastq    fastq/PPI_T0_R1_R2.fastq
1    PPI_T0_R2    fastq/PPI_T0_R2_R1.fastq    fastq/PPI_T0_R2_R2.fastq
2    PPI_T0_R3    fastq/PPI_T0_R3_R1.fastq    fastq/PPI_T0_R3_R2.fastq
3  Avail_T0_R1  fastq/Avail_T0_R1_R1.fastq  fastq/Avail_T0_R1_R2.fastq
4  Avail_T0_R2  fastq/Avail_T0_R2_R1.fastq  fastq/Avail_T0_R2_R2.fastq

In [ ]:
# Trim the reads in paired-end mode, using both side of the peptides to trim
df_file['Trimmed_file_F'] = ''
df_file['Trimmed_file_R'] = ''

for ind in df_file.index:
    
    cutadapt_call = 'cutadapt -a ACTGTCACTGACGCGGGAGGTGGAGCTAGC...aagcttattagttatgtcacgcttacattcacgccctc -A gagggcgtgaatgtaagcgtgacataactaataagctt...GCTAGCTCCACCTCCCGCGTCAGTGACAGT -o trim/'+str(df_file.loc[ind]['Sample_name'])+'_R1_trim.fastq -p trim/'+ str(df_file.loc[ind]['Sample_name'])+'_R2_trim.fastq '+ df_file.loc[ind]['R1_file']+ ' '+ df_file.loc[ind]['R2_file']
    subprocess.check_output(cutadapt_call, shell=True, stderr=subprocess.DEVNULL)
    df_file.at[ind, 'Trimmed_file_F'] = str(df_file.loc[ind]['Sample_name'])+'_R1_trim.fastq'
    df_file.at[ind, 'Trimmed_file_R'] = str(df_file.loc[ind]['Sample_name'])+'_R2_trim.fastq'

In [2]:
df_file = pd.read_csv('ref_file.csv')
df_file.head()

,Unnamed: 0,Sample_name,R1_file,R2_file,Trimmed_file_F,Trimmed_file_R,Merged_file,Agg_file
0,0,PPI_T0_R1,fastq/PPI_T0_R1_R1.fastq,fastq/PPI_T0_R1_R2.fastq,PPI_T0_R1_R1_trim.fastq,PPI_T0_R1_R2_trim.fastq,PPI_T0_R1.fasta,PPI_T0_R1_agg.fasta
1,1,PPI_T0_R2,fastq/PPI_T0_R2_R1.fastq,fastq/PPI_T0_R2_R2.fastq,PPI_T0_R2_R1_trim.fastq,PPI_T0_R2_R2_trim.fastq,PPI_T0_R2.fasta,PPI_T0_R2_agg.fasta
2,2,PPI_T0_R3,fastq/PPI_T0_R3_R1.fastq,fastq/PPI_T0_R3_R2.fastq,PPI_T0_R3_R1_trim.fastq,PPI_T0_R3_R2_trim.fastq,PPI_T0_R3.fasta,PPI_T0_R3_agg.fasta
3,3,Avail_T0_R1,fastq/Avail_T0_R1_R1.fastq,fastq/Avail_T0_R1_R2.fastq,Avail_T0_R1_R1_trim.fastq,Avail_T0_R1_R2_trim.fastq,Avail_T0_R1.fasta,Avail_T0_R1_agg.fasta
4,4,Avail_T0_R2,fastq/Avail_T0_R2_R1.fastq,fastq/Avail_T0_R2_R2.fastq,Avail_T0_R2_R1_trim.fastq,Avail_T0_R2_R2_trim.fastq,Avail_T0_R2.fasta,Avail_T0_R2_agg.fasta

In [3]:
###Call to merge read forward and read reverse
df_file['Merged_file'] = ''

for ind in df_file.index:
    
    panda_seq_call = 'pandaseq -f /home/david/PL_projects/sequencing/Screen_PPI_Avail_Feb2025/trim/'+df_file.loc[ind]['Trimmed_file_F']+' -r /home/david/PL_projects/sequencing/Screen_PPI_Avail_Feb2025/trim/'+df_file.loc[ind]['Trimmed_file_R']+' -l 10 -L 100 -T 6 -w /home/david/PL_projects/sequencing/Screen_PPI_Avail_Feb2025/merge/'+df_file.loc[ind]['Sample_name']+'.fasta'
    subprocess.check_output(panda_seq_call, shell=True, stderr=subprocess.DEVNULL)
    df_file.at[ind, 'Merged_file'] = str(df_file.loc[ind]['Sample_name'])+'.fasta'

In [4]:
df_file.head()

,Unnamed: 0,Sample_name,R1_file,R2_file,Trimmed_file_F,Trimmed_file_R,Merged_file,Agg_file
0,0,PPI_T0_R1,fastq/PPI_T0_R1_R1.fastq,fastq/PPI_T0_R1_R2.fastq,PPI_T0_R1_R1_trim.fastq,PPI_T0_R1_R2_trim.fastq,PPI_T0_R1.fasta,PPI_T0_R1_agg.fasta
1,1,PPI_T0_R2,fastq/PPI_T0_R2_R1.fastq,fastq/PPI_T0_R2_R2.fastq,PPI_T0_R2_R1_trim.fastq,PPI_T0_R2_R2_trim.fastq,PPI_T0_R2.fasta,PPI_T0_R2_agg.fasta
2,2,PPI_T0_R3,fastq/PPI_T0_R3_R1.fastq,fastq/PPI_T0_R3_R2.fastq,PPI_T0_R3_R1_trim.fastq,PPI_T0_R3_R2_trim.fastq,PPI_T0_R3.fasta,PPI_T0_R3_agg.fasta
3,3,Avail_T0_R1,fastq/Avail_T0_R1_R1.fastq,fastq/Avail_T0_R1_R2.fastq,Avail_T0_R1_R1_trim.fastq,Avail_T0_R1_R2_trim.fastq,Avail_T0_R1.fasta,Avail_T0_R1_agg.fasta
4,4,Avail_T0_R2,fastq/Avail_T0_R2_R1.fastq,fastq/Avail_T0_R2_R2.fastq,Avail_T0_R2_R1_trim.fastq,Avail_T0_R2_R2_trim.fastq,Avail_T0_R2.fasta,Avail_T0_R2_agg.fasta

In [5]:
###Call to get the number of read per unique sequence###

df_file['Agg_file'] = ''

for ind in df_file.index:
    
    vsearch_aggregate_call = '/home/david/PL_projects/tools/vsearch-2.30.0/bin/vsearch  --fastx_uniques /home/david/PL_projects/sequencing/Screen_PPI_Avail_Feb2025/merge/'+df_file.loc[ind]['Merged_file']+' --relabel seq --fastaout /home/david/PL_projects/sequencing/Screen_PPI_Avail_Feb2025/aggregated/'+df_file.loc[ind]['Sample_name']+'_agg.fasta --sizeout'
    subprocess.check_output(vsearch_aggregate_call, shell=True, stderr=subprocess.DEVNULL)
    df_file.at[ind, 'Agg_file'] = str(df_file.loc[ind]['Sample_name'])+'_agg.fasta'

In [ ]:
df_file.to_csv('reads_info.csv')